server:
  port: 8099
spring:
  datasource:
    jdbc-url: jdbc:mysql://127.0.0.1:13306/test?autoReconnect=true&useSSL=false
    username: root
    password: 123456
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    minimumIdle: 5
    maximumPoolSize: 10
    poolName: grassland-hikari
    connection-test-query: SELECT 1
  dubbo:
    application: grassland
    server: true
    registry:
      address: zookeeper://127.0.0.1:12181